# Generated by Django 4.2.6 on 2024-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chances_left',
            field=models.CharField(default='5', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lvl',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
