# Generated by Django 5.1.2 on 2024-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lvl',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
