# Generated by Django 5.1.2 on 2024-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_lvl'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('avg_time', models.CharField(max_length=30)),
            ],
        ),
    ]
