# Generated by Django 5.1.2 on 2024-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_leaderboard_eliminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
