# Generated by Django 4.2.6 on 2024-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('lvl', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=100)),
                ('chances_left', models.CharField(max_length=10)),
                ('started', models.CharField(default='0', max_length=5)),
            ],
        ),
    ]
