# Generated by Django 4.2.6 on 2024-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_chances_left_alter_userprofile_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='digits',
            field=models.CharField(default='NIL', max_length=1000),
        ),
    ]
