# Generated by Django 5.1.2 on 2024-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='eliminated',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
